# This is a basic workflow to help you get started with Actions

name: Test Name

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: "Environment (staging, prod)"
        required: true
        default: prod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test Run
    environment: ${{ inputs.env }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ${{ vars.DEMO_COMMIT_ID }}
          ${{ vars.STAGE_COMMIT_ID }}
          ${{ vars.PROD_COMMIT_ID }}
      
      - name: Update DEMO
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh variable set DEMO_COMMIT_ID --body ${{ github.sha }}
          
      - name: Update STAGE
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh variable set STAGE_COMMIT_ID --body ${{ github.sha }}
        
      - name: Update PROD
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh variable set PROD_COMMIT_ID --body ${{ github.sha }}
        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ${{ vars.DEMO_COMMIT_ID }}
          ${{ vars.STAGE_COMMIT_ID }}
          ${{ vars.PROD_COMMIT_ID }}
