# This is a basic workflow to help you get started with Actions

name: Test Name

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: "Environment (staging, prod)"
        required: true
        default: prod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test Run
    environment: ${{ inputs.env }}
    env:
      GH_TOKEN: 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
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ vars.TEST_VAR }}
      
      - name: Update VAR
        env:
          GITHUB_TOKEN: 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
        run: |
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/jlotito-scoir/test-repo/actions/variables/STAGE_COMMIT_ID \
          -f name='STAGE_COMMIT_ID' \
          -f value='2' 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
